import Layout from "../components/layout";
import Head from "next/head";

export default function Projects() {
  return (
    <>
      <Layout>
        <Head>
          <title>Centum_Joonho_Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </Layout>
    </>
  );
}
